apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: popsite-test
spec:
  generators:
    - matrix:
        generators:
          # git file generator referencing files containing details about each
          # app to be deployed (e.g., `appName`).
          - git:
              repoURL: https://github.com/xenbyte/helm-charts
              revision: HEAD
              files:
                - path: "charts/**/values/argo.json"
              pathParamPrefix: app
          # git file generator referencing files containing details about
          # locations to which each app should deploy (e.g., `region` and
          # `clusterName`).
          - git:
              repoURL: https://github.com/xenbyte/helm-charts
              revision: HEAD
              files:
                - path: "targets/{{appName}}/*.json"
              pathParamPrefix: target
  template:
    metadata:
      name: '{{appName}}-{{clusterName}}'
    spec:
      project: 'default'
      source:
        repoURL: 'https://github.com/xenbyte/helm-charts'
        path: 'charts/{{appName}}'
        targetRevision: HEAD
        helm:
          valueFiles:
            - 'values.yaml'
            - 'values/{{clusterName}}.yaml'

      destination:
        name: '{{clusterName}}'
        namespace: '{{appName}}'

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true

