apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/xenbyte/helm-charts
              revision: HEAD
              directories:
                - path: charts/*
          - clusters: {}

  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: 'default'
      source:
        repoURL: 'https://github.com/xenbyte/helm-charts'
        path: '{{path}}'
        targetRevision: HEAD
        helm:
          valueFiles:
            - 'values.yaml'
            - 'values/{{name}}.yml'

      destination:
        server: '{{server}}'
        namespace: '{{path.basename}}'

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true
